# .github/workflows/build-macos.yml

name: Build macOS App

on:
  push:
    branches:
      - main          # run on pushes to main
    tags:
      - 'v*'          # and on tags like v1.0-mac

jobs:
  build:
    runs-on: macos-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Download models & build
        run: |
          chmod +x build-macos.sh
          ./build-macos.sh

      - name: Upload macOS .app artifact
        uses: actions/upload-artifact@v2
        with:
          name: TranscriberApp-mac
          path: TranscriberApp-mac.zip
