# .github/workflows/build-macos.yml

name: Build macOS App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install & build
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          chmod +x build-macos.sh
          ./build-macos.sh

      - name: Upload macOS .app artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: TranscriberApp-mac
          path: TranscriberApp-mac.zip
